apiVersion: v1
kind: Namespace
metadata:
  name: netobserv-privileged
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-ebpf-agent
  namespace: netobserv-privileged
  labels:
    k8s-app: netobserv-ebpf-agent
spec:
  selector:
    matchLabels:
      k8s-app: netobserv-ebpf-agent
  template:
    metadata:
      labels:
        k8s-app: netobserv-ebpf-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-ebpf-agent
        image: localhost/ebpf-agent:test
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: SAMPLING
            value: "1"
          - name: CACHE_ACTIVE_TIMEOUT
            value: 200ms
          - name: LOG_LEVEL
            value: debug
          - name: FLOWS_TARGET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: FLOWS_TARGET_PORT
            value: "9999"
          - name: ENABLE_RTT
            value: "true"
          - name: ENABLE_PKT_DROPS
            value: "true"
          - name: ENABLE_DNS_TRACKING
            value: "true"
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
